[package]
name = "WebCrawler"
version = "0.1.0"
edition = "2021"

[dependencies]
cursive = "0.21"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }
scraper = "0.12"
vader_sentiment = "0.1.0"
futures = "0.3"
lazy_static = "1.4"